### ISSUE TITLE
#WPDiversity Allyship & Workshops Report

### ISSUE THREAD

**Issue by murillol** [WordPress/Marcomms-Rolling-tasks#13]
*Task*: Promote Report
Link: https://make.wordpress.org/community/2021/09/02/report-diverse-speaker-workshops-august-2021/
*Deadline*: ASAP
- [Published LinkedIn Post](https://www.linkedin.com/posts/make-wordpress-marketing-team_report-allyship-and-diverse-speaker-workshops-activity-6841031288376332288-gLgM)
- [Published Twitter Post](https://twitter.com/wordpressevents/status/1435528735919382528)

**Comment by murillol** [comment]
This was also included in the Community Month in WordPress August newsletter. People who worked on it were Abha, Nalini, Jill Binder, Larissa

**Comment by nalininsbs** [comment]
Props to: @jillb @murillol @abhansnuk @nalininsbs @meherbala
