### ISSUE TITLE
WordPress for Corporate Sized Entities

### ISSUE THREAD

**Issue by murillol** [WordPress/Marcomms-Rolling-tasks#22]
1: Objective: Help agencies persuade decision makers in corporate entities of the benefits of WordPress over other systems.
Working Document: https://docs.google.com/document/d/19HzURxeG-Y8vV5MZqmOUANyc1k4QDADvZDMnQjszFMw/edit#heading=h.nwa9lnlw5yv5

2: Done = 
-Buyer Persona CMO outlined
-Buyer persona CTO outlined
-Content needs for both outlined

3: Original Task-Lead: @yvettesonneveld 

_Timeline_
22 April 2020
Yvette to review latest position

**Comment by murillol** [comment]
Copied over from a Trello card: https://trello.com/c/NLZdbvAH

**Comment by Collieth** [comment]
This is a good piece of work. Would someone mind providing background on how the personas above (and bulleted out below were created? And how long ago it was was created, @abhansnuk @yvettesonneveld @murillol 



-Buyer Persona CMO outlined
-Buyer persona CTO outlined
-Content needs for both outlined

**Comment by yvettesonneveld** [comment]
Hey @Collieth, I'm sorry I just see this now. I still need to get into the habit of checking GitHub as regularly as I check Slack. This was created during the contributor day at WordCamp Europe 2021. We gathered a group of agency owners and marketers serving the enterprise market. We sat down with big sheets of paper and sticky notes and had very insightful conversations. I turned the sheets with sticky notes into this document a few weeks later and had it checked by several of the participants.

**Comment by abhansnuk** [comment]
Thanks Yvette. There are other persona work that have also been done at intervals and we can come back to post the release.
________________________________

**Comment by sereedmedia** [comment]
I've opened [an issue focused on revising the Enterprise page,](https://github.com/WordPress/Marketing-Team/discussions/244) which is essentially what this ticket is about as well. I've reference the doc above  (made at WCEU in 2019), so it is still accessible to the team. This specific ticket's closure has been announced for a few weeks in the weekly marketing meeting. I am closing it now and, if you want to talk on this topic, come over to https://github.com/WordPress/Marketing-Team/discussions/244.
