### ISSUE TITLE
2021/ Quarter 4 - WordPress Marketing

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marcomms-Rolling-tasks#26]
Drafted, submitted and published:
https://make.wordpress.org/updates/2021/04/15/quarterly-updates-q1-2021/

**Comment by nalininsbs** [comment]
Transferred to WP repo marketing-team board.

Props to:  @abhansnuk (webcommsat), @yvettesonneveld (yvettesonneveld), Maedah (maedahbatool), Harry Jackson (harryjackson1221), Mike Reid (@mikerbg), @OlaIola (OGlekler), @murillol (lmurillom), @nalininsbs (nalininonstopnewsuk) for contributing to this.
