### ISSUE TITLE
Notes Team Meeting 2021-09-15

### ISSUE THREAD

**Issue by murillol** [WordPress/Marcomms-Rolling-tasks#39]
**Notetaker**: @femkreations 

Link to Notes Doc: https://docs.google.com/document/d/1L2DZ5iaTEgjrbyc4pIda9-GPWbrFjdiLTKbZXSi4z-Y/

**Comment by murillol** [comment]
Hi @femkreations!

I know this is your first time doing notes, I think you'll find it a fun task :)
A few pointers:

- The team members who are doing the task updates and facilitating usually leave all information ready in the Notes document right before the Meeting
- What you should do after the meeting is go to the Notes Doc (link above) and just check that each update section matches with what was actually said in the meeting, that all the links are correct, and that whenever someone is mentioned in the notes, it’s with their WP ID, not with their Slack ID. 
- If there is something missing (for instance it was discussed in the Slack meeting but was not included in the Notes document), you can directly add it.
- If you don’t understand something or think it’s inaccurate, you can leave a comment on the document and Meher or I will answer!

**Comment by femkreations** [comment]
Completed the task

**Comment by nalininsbs** [comment]
Agenda: https://make.wordpress.org/marketing/2021/09/15/agenda-global-marketing-meeting-15-september-2021/
Props to @abhansnuk  and @murillol for working on items for the agenda and liaising with other teams. Thanks to @meherbala and @yvettesonneveld for following up on notes and actions.

Notes: https://make.wordpress.org/marketing/2021/09/20/notes-global-marketing-meeting-15-september-2021/ 
Props to @meherbala for writing the notes and @abhansnuk for reviewing
