### ISSUE TITLE
Yoast Contributor Days - 2021-10-08 & 2022-02-04

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marcomms-Rolling-tasks#43]
Joint session between marketing and training. 

Support the Learn. WordPress.org team with keyword research for future training material and create social media microcopy that can be used to promote the training sessions.

Yvette leading marketing table with Marketing/ Training contributors Hauwa and Courtney.

**Comment by abhansnuk** [comment]
**Documents for use - Social media drafting**
Quarter 4, 2021 LearnWP social media drafting document
https://docs.google.com/document/d/1icC42YaEnZc6Z9qco3tK-osPBLvbyHCK8lj4HrKIDhQ/edit?usp=sharing

Shared with the co-ordinating team members from marketing and training for use.

**Comment by abhansnuk** [comment]
Update from Hauwa:
The Marketing and Training (Learn WordPress) teams had a great session at the Yoast Contributor Day. Contributors assisted in preparing social media posts regarding the content on Learn WordPress, and also had a great discussion on the support for SEO planning around the content on Learn WordPress.

Thanks to Yoast for hosting a combined in-house and public contributor event, and to everyone that participated: Yvette Sonneveld, Abha Thakor Courtney Engle, Hauwa Abashiya, Nalini Thakor, Christopher Churchill, Caroline Nymark, Lotte Janssen, Amy Lees, Sam Alderson, Sabrina Joest.

**Actions:** Ongoing collaboration in the documents which were shared at Yoast's Contributor Day will continue in the Marketing channel. Dates to be confirmed.

**Comment by nalininsbs** [comment]
@yvettesonneveld could you please add any links necessary to this card, add the names of contributors, and close the card with comment. Thank you

**Comment by yvettesonneveld** [comment]
### We worked on:
-microcopy for social media posts
- did some testing with the social media image generator plugin. This plugin is planned to be included in JetPack soon, and will then be available in .org sites. 
- created a spreadsheet that will help with testing the performance of social media posts
- had a brainstorm about quick wins for the WordPress social media channels to accomplish their main objective: advancing the mission of WordPress: democratize publishing

### New folder
We have created a new folder in the .org marketing materials folder: [009 - Social media](https://drive.google.com/drive/folders/10CJchv9Y2fvPSzoyNbdWsxL8PI3WKOR1?usp=sharing)

In that folder, you'll find 

- a spreadsheet to help analyze the performance of social media posts
- a document with a summary of the brainstorm about opportunities for social media for the WordPress social media channels

### Participants: 
Courtney Robertson, Hauwa Abashiya, Judith Terbeek-Arts, Sam Alderson, Susan Wijdemans, Sabrina Joest, Tijana Andrejic, Kemi Makinde, Dan Soschin, Santana Innis, Reyes Martinez

**Comment by azhiya** [comment]
Thank you Yoast for organising this event. Glad that so many people were able to contribute.

**Comment by courtneyr-dev** [comment]
Thanks for organizing @yvettesonneveld and for the attendees that joined us.
