### ISSUE TITLE
2021/10 Polyglots newsletter (first edition)

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marcomms-Rolling-tasks#45]
**Background**
Monthly newsletter starting October 2021 to highlight what is happening with Polyglots Team and to help people find key information as the Polyglots slack channel and P2 (blog) are both very busy locations.

Sign-up promotion throughout WPTranslationDay 2021 (September 2021) and onwards through Polyglots and Marketing Team. Included in the Month in WordPress newsletter and to be shared in the Meetup Newsletter for October 2021.

- Monthly production cycle being created (Erica and Abha)

Nicholas offered to assist with Mailchimp etc

**Comment by abhansnuk** [comment]
Update posted by Erica 2021/10/15 in Marketing
- the first Polyglots monthly newsletter is now published - and emailed
https://make.wordpress.org/polyglots/2021/10/15/polyglots-monthly-newsletter-october-2021/
thank you so much for all of your helpful comments and feedback abhanonstopnewsuk, chaion07, EidolonNight!

Updates on social by @abhansnuk:
Twitter WPTD: done 15th 
Facebook WPTD: done 15th
More to follow. Social posts on WPTD spreadsheet.

**Comment by nalininsbs** [comment]
Props to: @varlese , @abhansnuk , @meherbala , @nalininsbs , @murillol , @OlaIola
