### ISSUE TITLE
Make WordPress Performance Team - AWARENESS

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marcomms-Rolling-tasks#52]
Proposal 2021/10 for a new team to help co-ordinate efforts to increase performance.  https://make.wordpress.org/core/2021/10/12/proposal-for-a-performance-team/

**Comment by abhansnuk** [comment]
2021/10/13 Promoting call for comments on proposal, once highlighted at DevChat https://twitter.com/wordpressevents/status/1448383001973465088?s=20

**Comment by nalininsbs** [comment]
@eidolonnight are any of your marketing colleagues working on this or liaising with the team? Could you mention them on the ticket. Is there anything still needed on this ticket or can it be closed for now? Thank you.

**Comment by abhansnuk** [comment]
Comment by @rmartinezduque on Slack. No one currently assigned from Nicholas' team. For now this ticket can be closed. For future promotion requests from the performance team (part of Core), this can be reopened or a new ticket added.
