### ISSUE TITLE
WPDiversity Allyship event 2021/11/17

### ISSUE THREAD

**Issue by murillol** [WordPress/Marcomms-Rolling-tasks#55]
Slack Thread: https://wordpress.slack.com/archives/C0GKJ7TFA/p1634342243293500

Allyship for WordPress event organizers AMER/EMEA
Wednesday, November 17, 2021
6pm-7pm UTC / 1pm-3pm ET
Free
(Tickets close 10 min before)

Key messages:
- Learn how to create welcoming and diverse WordPress Meetups and WordCamps for your WordPress community.
- This is not just for organizers, but anyone who wants to champion this kind of environment, now or in the future.
- An actionable workshop. You will leave with things that you can start doing right away.
https://www.eventbrite.com/e/allyship-for-wordpress-event-organizers-ameremea-tickets-187987905887

How to Own Your Expertise & Start Speaking at WordPress Events Southeast to Southern Asia
Saturday, November 27, 2021
0700H-0830H UTC / 1500H-1630 GMT+8 / 1230H-1400H IST
Free
(Tickets close 10 min before)

Key messages:
- For the Philippines, India, or other country nearby. (Southeast to Southern Asia)
- Do you identify as a person from a marginalized and underrepresented group (in terms of gender, race, class, caste, sexuality, ability, age, etc.) who is thinking about speaking at a Meetup or WordCamp?
- Do you think you don’t know or have anything worth speaking about?
https://www.eventbrite.com/e/how-to-own-your-expertise-start-speaking-at-wordpress-events-asia-tickets-191420663357

Jill put out a community post today with these and other workshops. Please note, the other workshops do not need the #marketing team on them.

**Comment by murillol** [comment]
**[Working Document is here](https://docs.google.com/document/d/1TDcEMhlsIuq9vSzA-XXQX8JYu-xjlzeOnBcDPvIG8hk/edit?usp=sharing)**. I have left the first drafts of the texts for both events for Facebook, LinkedIn and Twitter 
@abhansnuk please leave any edits and additions and let me know when I can schedule them in. Thank you!

**Comment by abhansnuk** [comment]
Thanks @murillol and @nalininsbs for the review and checking against the WPDiversity meetings.
I have edited and been through the comments. Will create and add a short link.

**Comment by nalininsbs** [comment]
@murillol can you please add any links to published items relating to this, and then close the card with the comment.

Part of our test of how props work on the new organization, adding them below. 
Props to: @abhansnuk , @nalininsbs , @murillol , @jillb

**Comment by murillol** [comment]
Hi! All the links to the published items [are in the Google Doc](https://docs.google.com/document/d/1TDcEMhlsIuq9vSzA-XXQX8JYu-xjlzeOnBcDPvIG8hk/edit#heading=h.esuopgo1wjb9). 

- [Wednesday 10 November 2021](https://www.facebook.com/wordpressevents/posts/285751730103248?__xts__[0]=68.ARC20C3MPkEhOZMSlej-XjzJC-qtpi2SiGmcyYoUO5ApMqIm6Uo3eDUXoh-zrMGXx9h_voH4wj0JaAFh-KhjWA6nrovfjHqXFbiTABA4nWLjxZlwsD1HUzTKgNiyh2tzr68LXhTs9Yb11-iLHaWcCBGolXSxVH3Zp-cqIg56efuhdxr8oE181qoKadGQgENY_t8UByPiQc_tgZQglygfOYsMGLf8Q9EjDdcqkInmZJXk0KcInKIvDNF0z1fJEzwHD17d5_iVjC4Ma4C84Es7PfxZNqtjgWp2D4ioZClk2P7wrbOOrHs&__xts__[1]=68.ARAVHYPIiQSj2xQUtjayOeYZbSDWxB6yNmT6vvED8TTYoAeSphHnaZ2sCoqYh-Lb3LnczNzc8-Em_yGwPHbJg3anfYNK90scQbRyCmVvrXw0KWfyi7hRMW-Iw0iQfI8RQwYgEel5Pc9B8x5VUxpZy0ZN6X-CmMO8ZkpD697uHWKrIqJBlT5XMaSme0TPHadB6B-vyOVSMxj6LH7edw7FVUbHs_qLXN6mHVFKztAB36Ym2BJJF0RgkQ6jab6urXz8nvI5JLD_OmUocQetN2eY9Hc2OFdXFeU9iQrDRhICIP8LFy5VDYQ) 11.15 UTC
- [Tuesday 9 November 2021](https://twitter.com/wordpressevents/status/1458147937188564995) 7.00pm UTC
