### ISSUE TITLE
Notes team meeting 2021-07-21

### ISSUE THREAD

**Issue by murillol** [WordPress/Marcomms-Rolling-tasks#56]
**Note Taker**: @yashwardhanrana 
**Note Reviewer**: @lmurillom 
**Final Editor**: @abhansnuk 

Agenda for Meeting: https://wp.me/p72A3H-1Xp
Meeting Slack Link: https://wordpress.slack.com/archives/C0GKJ7TFA/p1626875967306600

**[Published Meeting Notes on P2](https://make.wordpress.org/marketing/2021/07/27/notes-global-marketing-meeting-21-july-2021/)**

- [x] Notes in Google Doc correspond to P2?

**Comment by nalininsbs** [comment]
Props to: @yashwardhanrana @murillol @abhansnuk
