### ISSUE TITLE
Weekly marketing team agendas and week planning cards

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marcomms-Rolling-tasks#6]
Agendas are published on the Marketing Team blog (known as the P2) on Make.wordpress.org before the weekly global meeting in Wednesdays. These ideally need to be published by Tuesday to help those using assistive technology or in different timezones.

Once published on the blog, team reps will add the post to the ‘highlight’ category so that it appears on the homepage box of the blog.

To help the agenda planning, in the two days before the meeting and at the previous week’s meeting, requests are made in the Marketing slack for:
- updates on particular tasks or space for a collaboration
- links from other teams which have a marketing aspect or potential action
- during a release, members attending devchat are asked to share any relevant links / calls to include in the agenda
- in deadline / action periods on the release relating to marketing, agenda items are requested from Josepha or Chloe / release group on slack
- any suggestions for agenda items relating to the team 
- etc.

After the meeting in slack, we are now adding a link to the start of the discussion on slack to the agenda post to further help asynchronous contribution and assist notetakers. 

For accessibility and asynchronous contribution across timezones, we have been asked to use agenda numbering when posting updates during a slack meeting. This also assists those new to slack and/ or the team.

**Comment by meherbala** [comment]
One point which needs to be added to the agenda is Coffee break time change poll.

**Comment by nalininsbs** [comment]
Note this is not a task that has to be done by team reps alone. In the past, other contributors have assisted in finding relevant links, adding / suggesting items for update.

**Comment by nalininsbs** [comment]
Created a number of new cards for meetings in August. Updated the descriptor and checklist information for cards.

All things related to this meeting and any collaborations during the week, including:

- planning
- suggestions for items and agenda drafting, including suggesting items for Open Floor
- check the [diary dates post](https://make.wordpress.org/marketing/2021/01/13/forthcoming-diary-dates/) has been updated
- any asynchronous update on tasks
- script to assist the running of the meeting
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources
- any updates to the team Google calendar on planned collaborations

**Useful links:**
[Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)

[Coffee break rota](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by nalininsbs** [comment]
Shall we add names to who is facilitating the next coffee break on the weekly agenda cards to acknowledge them and volunteering for this @murillol and @eidolonnight ? The next few coffee breaks rota are saved on the coffee break card. I moved this to being a macro card.
