### ISSUE TITLE
Promote FSE Outreach call for testing #11 through November 30th

### ISSUE THREAD

**Issue by annezazu** [WordPress/Marcomms-Rolling-tasks#65]
Request to have you all help promote the latest FSE outreach call for testing ahead of 5.9: https://make.wordpress.org/test/2021/11/08/fse-program-testing-call-11-site-editing-safari/

Thanks so much!

**Comment by murillol** [comment]
**Proposed Copy** 

_LinkedIn_
Join the final call for testing before WordPress 5.9! Your participation will help improve the experience for a large portion of the web. 
This test goes over a lot, so get ready to explore various site editing flows, design tools and editing specific template parts.
Please amplify this call for testing by sharing with your networks! 

https://make.wordpress.org/test/2021/11/08/fse-program-testing-call-11-site-editing-safari/

#WordPress #FullSiteEditing

**Comment by murillol** [comment]
@abhansnuk can you give this a quick check pls

**Comment by murillol** [comment]
pinging @abhansnuk  👯

**Comment by nalininsbs** [comment]
Props to:  @annezazu , @murillol , @megphillips91 , @abhansnuk , @meherbala , @OlaIola for contributions on this
