### ISSUE TITLE
WPDiversity workshop, 9 December 2021

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marcomms-Rolling-tasks#70]
2021/11/17 [Link to initial briefing to marketing from WPDiversity](https://wordpress.slack.com/archives/C0GKJ7TFA/p1637118652273400)

**Event info received with marketing info**
How to Own Your Expertise & Start Speaking at WordPress Events AMER/EMEA
Thursday, December 9, 2021
6-8pm UTC
Free

- Tickets close 15 min before
- Audience: - For Americas and Europe

Key messages update for this event from Jill Binder:

- Do you identify as a person from a marginalized and underrepresented group (in terms of gender, race, class, caste, sexuality, ability, age, etc.) who is thinking about speaking at a Meetup or WordCamp?
- Do you think you don’t know or have anything worth speaking about?
- Do you feel nervous about speaking?
- Do you have stage fright?
- Meetup and WordCamp organizers: Would you like to have more public speakers put their hand up to speak, especially people from underrepresented groups? Invite your community to this!

**Event links**
Full link on Eventbrite: https://www.eventbrite.com/e/how-to-own-your-expertise-start-speaking-at-wordpress-events-ameremea-tickets-212148661357

Short link to use in promotions:  https://bit.ly/WPDiversity9Dec2021
[shared with Jill 2021/11/17)

**Comment by jillb** [comment]
@murillol @abhansnuk @nalininsbs 

There has been a chance of plans. As we get to the end of this year that was the busiest year yet, a year filled with many workshops and expanding our programs from one to three, we decided it makes more sense to save our workshop energy for the new year and new year’s resolutions in January.

So we are going to cancel the December 9, 2021 Diverse Speaker workshop.

Thank you for what you have already put into the December 9 workshop, and thank you for your flexibility and understanding!

**Comment by abhansnuk** [comment]
Thanks @jillb . We will get on this. 

Actions:
- unschedule Fb promotions on WordCamp and WordPress Events (Abha)
- remove Fb event entry on WordPress Events (Abha)
- update in comment, if we can not in the post, previous Fb post about the event (Abha)
- remove the LinkedIn promotion that went out 1/12/21 (Abha)
- unschedule the Twitter promotions (Larissa)
- change references to promotions in P2 list 
- anything else @murillol and @nalininsbs ?

**Comment by murillol** [comment]
I do not see anything in the Twitter scheduler so we can check that off 👍

**Comment by nalininsbs** [comment]
Props to the people mentioned in this ticket
