### ISSUE TITLE
Upload and check subtitles, Gautam video short, Polyglot/ WPTD

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marcomms-Rolling-tasks#77]
To do: 
- Upload the video file onto WP Marketing Team YouTube and set descriptors and settings. List as private until all ready to go live as otherwise it will not go out on the RSS feed
- Check with Gautam on new contributor info to include in story on descriptor and for sentence in the Polyglot newsletter
- Check subtitles setting uses the ones Hari has done on the video itself
- Add to WP Translation playlist
- If locale has a P2 site, share embed code set to Playlist in rel=0
- Send locale social posts links once issued with request for them to reshare 
- Hashtags #WPTranslationDay #WordPress #ContributorStory

Deadlines:
- Needs to be published ready for January 2022 edition of Polyglots Newsletter. Link to go to Erica.
- Give to Meher or Erica for WPTranslationDay website

For info: @varlese @meherbala Hari

**Comment by nalininsbs** [comment]
Test adding this to a replica board under WordPress organization

**Comment by nalininsbs** [comment]
Test successful on this card. Can now update this card under the new organization.

@OlaIola will you still be able to help with this task? Thank you

**Comment by nalininsbs** [comment]
Copying into this card documentation by @abhansnuk 

**Step 1**
Writing the subtitles for this video is an easy first task for a new contributor. If you would like to volunteer to do this, please add a comment to this card. To keep it simple, copy your subtitles directly into this card as a first step. 

[Where a video version has been provided in a local language, discuss subtitles with the contributor, and check synchronization with them]

**Step 2**
Merge the subtitles with the video, and testing.

**Step 3**
Update the video description and link to WPTranslationDay 2021 write-up.

**Step 4**
Produce an image for the polyglots newsletter and an embed file with rel=0
Share with polyglots

**Step 5**
Add to WPTranslationDay website

**Step 6**
After the polyglot newsletter is published, share on WPTranslation Day social media.

**Comment by Ad-Mk** [comment]
Hi,
I'd like to volunteer for the task.

**Comment by Ad-Mk** [comment]
Kindly share the video link, as I cannot find it in the above thread. Also, do share the relevant details pertaining to the task.
Thanks!

(Btw I'm new to this space, so still getting used to the whole workflow and procedure. Any help would be deeply appreciated!)

**Comment by nalininsbs** [comment]
Hello @Ad-Mk and welcome. Thanks for your questions on Slack on getting involved too. We are pleased to be able to help.
The video link is to the original file, so this can sent to you directly. We do not post original video links on GitHub as they can get deleted or edited in error as the cards are accessible to anyone on the internet. Thank you.

**Comment by nalininsbs** [comment]
@Ad-Mk this is an example of how the subtitles appear https://www.youtube.com/watch?v=VsiQzdmAz8g for this series of videos.

**Comment by Ad-Mk** [comment]
Just saw the video, and it looks great!
Let me know how you want me to proceed with this and any particular tools, procedure, etc I need to follow.

Thanks!

**Comment by nalininsbs** [comment]
I will ask @abhansnuk or Olga to set you up with a link for a google document where you can add subtitles text from playing the video. I am reading the auto captions produced and they are of no use unfortunately.

You can use any video software to edit the file as long as it does not reduce the resolution beyond what can be used. Please create a copy in the folder (link has been sent to you) and mark it edit with your initials at the end of the filename.  Can you blur the name of the equipment in the corner.

We did have beginning and end slides for these videos. I will ask the designer who did these to add them to this card for you. These do not have to be ready for the newsletter as it has a deadline of Monday, but can be added later. The priority is having the video edited, subtitled, merged for timing, ready on YouTube, and the image created and embed file for the newsletter. Naoko is working to Monday for additions to the video. Would this timing work for you? We can find an alternative for Naoko if not.

Glad to have you on board. Thank you.

**Comment by Ad-Mk** [comment]
Thanks a lot for the welcome. I'll start working on the same. 
So the deadline is Monday, right?

**Comment by abhansnuk** [comment]
Published in newsletter https://make.wordpress.org/polyglots/2022/03/22/polyglots-monthly-newsletter-march-2022/

[WordPress Polyglot Gautam Navada shares the benefit of translating software into a local language.](https://www.youtube.com/watch?v=cx5CU5vrAAc)

Could you make a video or share your story on why you translate WordPress? Contact the [#marketing](https://wordpress.slack.com/archives/C0GKJ7TFA) channel on the Make WordPress Slack and tag team rep nalininonstopnewsuk

You can find more polyglots-related content on the [WordPress Translation Day playlist on YouTube](https://www.youtube.com/playlist?list=PLCVEqsAbLfffK5WzOT9BhPsh82HgM8vj1) [#WPTranslationDay](https://make.wordpress.org/polyglots/tag/wptranslationday/)

Contributors to editing and captioning this video: @abhansnuk , @Ad-Mk
