### ISSUE TITLE
2021/12 Month in WordPress December

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marcomms-Rolling-tasks#80]
(Deadline: December 30, 2021)

Note from @anjanavasan in Slack: If anyone would like to highlight something in the next edition of the Month in WordPress or the newsletter for meetup organizers, please enter it in the following documents by the date mentioned below:
[Submissions for the Month in WordPress](https://docs.google.com/document/d/1TbIQQIMj6_8wa18Ay2IuTQVKHkH4rjE-AK-EmXb27Io/edit?usp=sharing) (due by December 30, 2021)
[Submissions for the newsletter for meetup organizers](https://docs.google.com/document/d/1bwzmpoNlEcLx0vmYUCCtI6JuUvr-dSYhm3p6PGpXiIs/edit?usp=sharing) (due by January 5, 2022)

**Comment by nalininsbs** [comment]
Published: https://wordpress.org/news/2022/01/the-month-in-wordpress-december-2021/ 

Contributors (note below are WP.org IDs)
anjanavasan, harishanker, lmurillom, meher, webcommsat
