### ISSUE TITLE
Global Marketing Meeting 2022/02/16

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marcomms-Rolling-tasks#90]
- preparation
- agenda
- notes

**Comment by nalininsbs** [comment]
Planning discussion on GitHub https://github.com/WordPress/Marcomms-Internal-Comms/discussions/14

Agenda https://make.wordpress.org/marketing/2022/02/16/agenda-global-marketing-team-16-february-2022/ 

Script https://docs.google.com/document/d/1AhuFm25ZfZwyywkA4dgzfNVrdNAZ8sETB7u4nKiDGlc/edit#

**Comment by sereedmedia** [comment]
This meeting has passed.
